// Generated code - manual workaround for retrofit_generator compatibility issue
// This file is generated by retrofit code generation.
// This is the compiled _ApiClient implementation.

part of 'api_client.dart';

class _ApiClient implements ApiClient {
  _ApiClient(
    this._dio, {
    this.baseUrl,
  }) {
    baseUrl ??= 'https://www.elsfm.com/api/v1';
  }

  final Dio _dio;

  String? baseUrl;

  @override
  Future<BackendResponse<List<Channel>>> getChannels() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<BackendResponse<List<Channel>>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/channel',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = BackendResponse<List<Channel>>.fromJson(
        _result.data!,
        (json) => (json as List<dynamic>)
            .map<Channel>((i) => Channel.fromJson(i as Map<String, dynamic>))
            .toList(),
      );
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<BackendResponse<Map<String, dynamic>>> getChannel(int id) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<BackendResponse<Map<String, dynamic>>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/channel/$id',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = BackendResponse<Map<String, dynamic>>.fromJson(
        _result.data!,
        (json) => json as Map<String, dynamic>,
      );
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<PaginationResponse<Artist>> getArtists({
    int page = 1,
    int perPage = 20,
  }) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'page': page,
      r'per_page': perPage,
    };
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<PaginationResponse<Artist>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/artists',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = PaginationResponse<Artist>.fromJson(
        _result.data!,
        (json) => Artist.fromJson(json as Map<String, dynamic>),
      );
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<Map<String, dynamic>> getArtist(
    int id, {
    String loader = 'artist',
  }) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{r'loader': loader};
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Map<String, dynamic>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/artists/$id',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    return _result.data!;
  }

  @override
  Future<PaginationResponse<Track>> getArtistTracks(
    int id, {
    int page = 1,
    int perPage = 20,
  }) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'page': page,
      r'per_page': perPage,
    };
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<PaginationResponse<Track>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/artists/$id/tracks',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = PaginationResponse<Track>.fromJson(
        _result.data!,
        (json) => Track.fromJson(json as Map<String, dynamic>),
      );
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<PaginationResponse<Album>> getArtistAlbums(
    int id, {
    int page = 1,
    int perPage = 20,
  }) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'page': page,
      r'per_page': perPage,
    };
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<PaginationResponse<Album>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/artists/$id/albums',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = PaginationResponse<Album>.fromJson(
        _result.data!,
        (json) => Album.fromJson(json as Map<String, dynamic>),
      );
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<PaginationResponse<Album>> getAlbums({
    int page = 1,
    int perPage = 20,
  }) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'page': page,
      r'per_page': perPage,
    };
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<PaginationResponse<Album>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/albums',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = PaginationResponse<Album>.fromJson(
        _result.data!,
        (json) => Album.fromJson(json as Map<String, dynamic>),
      );
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<Map<String, dynamic>> getAlbum(int id) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Map<String, dynamic>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/albums/$id',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    return _result.data!;
  }

  @override
  Future<Track> getTrack(int id) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Track>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/tracks/$id',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = Track.fromJson(_result.data!);
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<PaginationResponse<Playlist>> getPlaylists({
    int page = 1,
    int perPage = 20,
  }) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'page': page,
      r'per_page': perPage,
    };
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<PaginationResponse<Playlist>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/playlists',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = PaginationResponse<Playlist>.fromJson(
        _result.data!,
        (json) => Playlist.fromJson(json as Map<String, dynamic>),
      );
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<Map<String, dynamic>> getPlaylist(int id) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Map<String, dynamic>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/playlists/$id',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    return _result.data!;
  }

  @override
  Future<Map<String, dynamic>> search({
    required String query,
    String type = 'track,artist,album,playlist',
    int limit = 20,
  }) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'q': query,
      r'type': type,
      r'limit': limit,
    };
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<Map<String, dynamic>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/search',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    return _result.data!;
  }

  @override
  Future<User> getCurrentUser() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<User>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/user',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = User.fromJson(_result.data!);
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<PaginationResponse<Track>> getLikedTracks(
    int userId, {
    int page = 1,
    int perPage = 20,
  }) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'page': page,
      r'per_page': perPage,
    };
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<PaginationResponse<Track>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/users/$userId/liked-tracks',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = PaginationResponse<Track>.fromJson(
        _result.data!,
        (json) => Track.fromJson(json as Map<String, dynamic>),
      );
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<PaginationResponse<Album>> getLikedAlbums(
    int userId, {
    int page = 1,
    int perPage = 20,
  }) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'page': page,
      r'per_page': perPage,
    };
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<PaginationResponse<Album>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/users/$userId/liked-albums',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = PaginationResponse<Album>.fromJson(
        _result.data!,
        (json) => Album.fromJson(json as Map<String, dynamic>),
      );
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<PaginationResponse<Playlist>> getUserPlaylists(
    int userId, {
    int page = 1,
    int perPage = 20,
  }) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'page': page,
      r'per_page': perPage,
    };
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
      _setStreamType<PaginationResponse<Playlist>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/users/$userId/playlists',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    late final value;
    try {
      value = PaginationResponse<Playlist>.fromJson(
        _result.data!,
        (json) => Playlist.fromJson(json as Map<String, dynamic>),
      );
    } on Object catch (e, st) {
      throw DioException(
        requestOptions: _result.requestOptions,
        response: _result,
        type: DioExceptionType.unknown,
        error: e,
        stackTrace: st,
      );
    }
    return value;
  }

  @override
  Future<List<Genre>> getGenres() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<List<dynamic>>(
      _setStreamType<List<Genre>>(
        Options(
          method: 'GET',
          headers: _headers,
          extra: _extra,
        )
            .compose(
              _dio.options,
              '/genres',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl),
      ),
    );
    var value = (_result.data!)
        .map<Genre>((i) => Genre.fromJson(i as Map<String, dynamic>))
        .toList();
    return value;
  }

  RequestOptions _setStreamType<T>(RequestOptions requestOptions) {
    if (T != String) {
      return requestOptions.copyWith(responseType: ResponseType.json);
    }
    return requestOptions.copyWith(responseType: ResponseType.stream);
  }
}
